version: "3.9"

services:
  pr-manager-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pr-manager-postgres
    ports:
      - "8080:8080"
    networks:
      - pr-manager-network
    restart: unless-stopped

  pr-manager-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pr_manager_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pr-manager-network
    restart: unless-stopped

networks:
  pr-manager-network:

volumes:
  pr_manager_postgres_data:
